types:
  Tone:
    $id: "aiwf://common/Tone"
    type: string
    enum: [dark, hopeful, playful, mysterious]

  DateRange:
    $id: "aiwf://common/DateRange"
    type: object
    required: [start, end]
    properties:
      start: { type: string, format: date }
      end:   { type: string, format: date }
