version: 0.2

imports:
  - as: common
    path: ./common.types.yaml
  - as: book
    path: ./book.types.yaml

assistants:
  premise:
    model: gpt-4.1-mini
    # Вариант 1: встроенный промпт
    system_prompt: |
      Ты — автор идей для художественных произведений.
      Придумай короткий логлайн и список тематик.
    output_schema_ref: "aiwf://book/PremiseOutput"

  outline:
    model: gpt-4.1
    # Вариант 2: ссылка на внешний файл
    system_prompt_ref: prompts/outline.md
    input_schema_ref: "aiwf://book/OutlineInput"
    output_schema_ref: "aiwf://book/OutlineOutput"

threads:
  default:
    provider: openai_assistants
    strategy: append       # append (каждое сообщение шага добавляется в историю) | reset_before_step (перед шагом история очищается/логически отделяется (в провайдерах, где это доступно))
    create: true           # создать при старте
    close_on_finish: false # закрывать после воркфлоу
    metadata:
      project: "novel"
      ttl_hours: 24

workflows:
  novel:
    thread: default        # весь воркфлоу использует общий тред
    dag:
      - step: premise
        assistant: premise
        thread:
          use: default     # можно переопределить на уровне шага
          strategy: append
        approval:
          review:
            strictness: 7
            prompt: "Проверь целостность идеи, уникальность, соответствие жанру."
            properties:
              "logline": { prompt: "≤160 символов, без спойлеров.", strictness: 8 }
              "themes[]": { prompt: "1–3 слова, без повторов.",      strictness: 6 }
              "tone": { prompt: "dark/hopeful/playful.",         strictness: 9 }
          require_for_retry: true
          max_retries: 3
          on_approve: { action: goto, step: outline }  # { action: continue | retry | goto | stop, step: <stepName?> }
          on_reject: { action: retry } # { continue | retry | goto | stop,      step: <stepName?> }
        next:
          step: outline
          input_binding: # как собирать вход следующего шага
            premise: "{{ .Premise }}"      # свободный шаблон
          input_contract_ref: "aiwf://book/OutlineInput"
      - step: outline
        assistant: outline
        thread:
          use: default
          strategy: append
