version: 0.1
schema_registry:
  root: schemas

assistants:
  market_research:
    model: gpt-4o-mini
    system_prompt: |
      You are a research strategist. Synthesize audience insights, surface 2-3 segments, and highlight pains plus preferred channels.
    input_schema_ref: research_input.json
    output_schema_ref: research_output.json

  value_proposition:
    model: gpt-4o-mini
    system_prompt: |
      You convert research findings into differentiated value propositions. Draft crisp positioning for each segment.
    input_schema_ref: proposition_input.json
    output_schema_ref: proposition_output.json

  content_strategy:
    model: gpt-4o
    system_prompt: |
      You design integrated launch strategies. Transform value propositions into concrete channel plays with cadence and KPIs.
    input_schema_ref: strategy_input.json
    output_schema_ref: strategy_output.json

  launch_timeline:
    model: gpt-4o
    system_prompt: |
      You are an operations lead. Map the launch plan into weekly milestones with owners and deliverables.
    input_schema_ref: timeline_input.json
    output_schema_ref: timeline_output.json

  risk_assessment:
    model: gpt-4o-mini
    system_prompt: |
      You analyze plans for operational and market risks. Provide mitigations and metrics to monitor.
    input_schema_ref: risk_input.json
    output_schema_ref: risk_output.json

workflows:
  campaign_launch:
    description: Plan a multi-channel product launch campaign with research, messaging, content, execution timeline, and risk plan.
    dag:
      - step: research
        assistant: market_research
      - step: messaging
        assistant: value_proposition
        needs: [research]
      - step: strategy
        assistant: content_strategy
        needs: [messaging]
      - step: timeline
        assistant: launch_timeline
        needs: [strategy]
      - step: risks
        assistant: risk_assessment
        needs: [timeline, strategy]
