// Code generated by aiwf. DO NOT EDIT.

package aiwfgen

// UserRequest represents UserRequest
type UserRequest struct {
	Text string `json:"text"`
	Mode string `json:"mode"`
}

// ExtractedData represents ExtractedData
type ExtractedData struct {
	Metadata map[string]interface{} `json:"metadata"`
	Entities []*Entity `json:"entities"`
	Count int `json:"count"`
}

// Entity represents Entity
type Entity struct {
	Name string `json:"name"`
	Type string `json:"type"`
	Confidence float64 `json:"confidence"`
}

// ============ VALIDATORS ============

// ValidateUserRequest validates UserRequest
func ValidateUserRequest(v *UserRequest) error {
	// No validation rules
	return nil
}

// ValidateExtractedData validates ExtractedData
func ValidateExtractedData(v *ExtractedData) error {
	// No validation rules
	return nil
}

// ValidateEntity validates Entity
func ValidateEntity(v *Entity) error {
	// No validation rules
	return nil
}

// ============ TYPE METADATA ============

// TypeMetadata exports type definitions for providers
var TypeMetadata = map[string]interface{}{
	"ExtractedData": nil, // TODO: export actual TypeDef
	"Entity": nil, // TODO: export actual TypeDef
	"UserRequest": nil, // TODO: export actual TypeDef
}
