// Code generated by aiwf. DO NOT EDIT.

package metasdk

import (
	"fmt"

	"github.com/andranikuz/aiwf/runtime/go/aiwf"
)

// Service provides access to all agents
type Service struct {
	client        aiwf.ModelClient
	threadManager aiwf.ThreadManager
	artifactStore aiwf.ArtifactStore
	agents        *Agents
}

// NewService creates a new service instance
func NewService(client aiwf.ModelClient) *Service {
	s := &Service{
		client: client,
	}

	// Initialize agents
	task_analyzerAgent := NewTaskAnalyzerAgent(client)
	task_analyzerAgent.Types = s // Inject TypeProvider
	yaml_generatorAgent := NewYamlGeneratorAgent(client)
	yaml_generatorAgent.Types = s // Inject TypeProvider

	s.agents = &Agents{
		YamlGenerator: yaml_generatorAgent,
		TaskAnalyzer: task_analyzerAgent,
	}

	return s
}

// WithThreadManager sets the thread manager
func (s *Service) WithThreadManager(tm aiwf.ThreadManager) *Service {
	s.threadManager = tm
	return s
}

// WithArtifactStore sets the artifact store
func (s *Service) WithArtifactStore(store aiwf.ArtifactStore) *Service {
	s.artifactStore = store
	return s
}

// Agents returns the agents instance
func (s *Service) Agents() *Agents {
	return s.agents
}

// ============ TYPE PROVIDER IMPLEMENTATION ============

// GetTypeMetadata returns metadata for a type
func (s *Service) GetTypeMetadata(typeName string) (any, error) {
	if meta, ok := TypeMetadata[typeName]; ok {
		return meta, nil
	}
	return nil, fmt.Errorf("type %s not found", typeName)
}

// GetInputTypeFor returns input type for an agent
func (s *Service) GetInputTypeFor(agentName string) (string, any, error) {
	switch agentName {
	case "task_analyzer":
		return "string", TypeMetadata["string"], nil
	case "yaml_generator":
		return "GenerationInput", TypeMetadata["GenerationInput"], nil
	default:
		return "", nil, fmt.Errorf("agent %s not found", agentName)
	}
}

// GetOutputTypeFor returns output type for an agent
func (s *Service) GetOutputTypeFor(agentName string) (string, any, error) {
	switch agentName {
	case "task_analyzer":
		return "TaskAnalysis", TypeMetadata["TaskAnalysis"], nil
	case "yaml_generator":
		return "GeneratedConfig", TypeMetadata["GeneratedConfig"], nil
	default:
		return "", nil, fmt.Errorf("agent %s not found", agentName)
	}
}

// ============ THREAD MANAGEMENT ============

// StartGenerationContextThread starts a new generation_context thread
func (s *Service) StartGenerationContextThread() (*aiwf.ThreadState, error) {
	if s.threadManager == nil {
		return nil, fmt.Errorf("thread manager not configured")
	}
	return s.threadManager.Start(nil, "", aiwf.ThreadBinding{
		Name:     "generation_context",
		Provider: "openai",
		Strategy: "append",
	})
}

