// Code generated by aiwf. DO NOT EDIT.

package metasdk

// ValidationNote represents ValidationNote
type ValidationNote struct {
	Severity string `json:"severity"`
	Message string `json:"message"`
	Field string `json:"field"`
}

// AgentSpec represents AgentSpec
type AgentSpec struct {
	Role string `json:"role"`
	Model string `json:"model"`
	Reasoning string `json:"reasoning"`
	Name string `json:"name"`
	InputDescription string `json:"input_description"`
	NeedsDialog bool `json:"needs_dialog"`
	MaxDialogRounds int `json:"max_dialog_rounds"`
	Provider string `json:"provider"`
	OutputDescription string `json:"output_description"`
}

// GenerationInput represents GenerationInput
type GenerationInput struct {
	Analysis string `json:"analysis"`
	RefinementInstructions string `json:"refinement_instructions"`
	UserAnswers map[string]string `json:"user_answers"`
}

// TypeDefinition represents TypeDefinition
type TypeDefinition struct {
	Description string `json:"description"`
	Name string `json:"name"`
	Fields []*FieldDefinition `json:"fields"`
}

// GeneratedConfig represents GeneratedConfig
type GeneratedConfig struct {
	YamlContent string `json:"yaml_content"`
	Notes []string `json:"notes"`
	TypeCount int `json:"type_count"`
	Types []*TypeDefinition `json:"types"`
	GeneratedAt string `json:"generated_at"`
	AgentCount int `json:"agent_count"`
	ValidationStatus string `json:"validation_status"`
	ValidationNotes []*ValidationNote `json:"validation_notes"`
	ImprovementSuggestions []string `json:"improvement_suggestions"`
	Version string `json:"version"`
	Assistants []*AssistantConfig `json:"assistants"`
}

// ClarificationQuestion represents ClarificationQuestion
type ClarificationQuestion struct {
	Question string `json:"question"`
	Reason string `json:"reason"`
	Suggestions []string `json:"suggestions"`
}

// TaskAnalysis represents TaskAnalysis
type TaskAnalysis struct {
	Summary string `json:"summary"`
	NeedsClarification bool `json:"needs_clarification"`
	ArchitectureNotes string `json:"architecture_notes"`
	AgentCount int `json:"agent_count"`
	DataTypesNeeded []string `json:"data_types_needed"`
	ImplementationHints []string `json:"implementation_hints"`
	Complexity string `json:"complexity"`
	ComplexityScore float64 `json:"complexity_score"`
	Agents []*AgentSpec `json:"agents"`
	Questions []*ClarificationQuestion `json:"questions"`
	RequiresThread bool `json:"requires_thread"`
	RequiresDialog bool `json:"requires_dialog"`
}

// AssistantConfig represents AssistantConfig
type AssistantConfig struct {
	Use string `json:"use"`
	Model string `json:"model"`
	OutputType string `json:"output_type"`
	MaxTokens int `json:"max_tokens"`
	Temperature float64 `json:"temperature"`
	Name string `json:"name"`
	SystemPrompt string `json:"system_prompt"`
	NeedsDialog bool `json:"needs_dialog"`
	DialogMaxRounds int `json:"dialog_max_rounds"`
	InputType string `json:"input_type"`
	NeedsThread bool `json:"needs_thread"`
}

// FieldDefinition represents FieldDefinition
type FieldDefinition struct {
	FieldName string `json:"field_name"`
	FieldType string `json:"field_type"`
}

// ============ VALIDATORS ============

// ValidateClarificationQuestion validates ClarificationQuestion
func ValidateClarificationQuestion(v *ClarificationQuestion) error {
	// No validation rules
	return nil
}

// ValidateTaskAnalysis validates TaskAnalysis
func ValidateTaskAnalysis(v *TaskAnalysis) error {
	// No validation rules
	return nil
}

// ValidateAssistantConfig validates AssistantConfig
func ValidateAssistantConfig(v *AssistantConfig) error {
	// No validation rules
	return nil
}

// ValidateFieldDefinition validates FieldDefinition
func ValidateFieldDefinition(v *FieldDefinition) error {
	// No validation rules
	return nil
}

// ValidateValidationNote validates ValidationNote
func ValidateValidationNote(v *ValidationNote) error {
	// No validation rules
	return nil
}

// ValidateAgentSpec validates AgentSpec
func ValidateAgentSpec(v *AgentSpec) error {
	// No validation rules
	return nil
}

// ValidateGenerationInput validates GenerationInput
func ValidateGenerationInput(v *GenerationInput) error {
	// No validation rules
	return nil
}

// ValidateTypeDefinition validates TypeDefinition
func ValidateTypeDefinition(v *TypeDefinition) error {
	// No validation rules
	return nil
}

// ValidateGeneratedConfig validates GeneratedConfig
func ValidateGeneratedConfig(v *GeneratedConfig) error {
	// No validation rules
	return nil
}

// ============ TYPE METADATA ============

// TypeMetadata exports type definitions for providers
var TypeMetadata = map[string]interface{}{
	"AgentSpec": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"name": map[string]interface{}{
		"type": "string",
	},
			"input_description": map[string]interface{}{
		"type": "string",
	},
			"needs_dialog": map[string]interface{}{
		"type": "boolean",
	},
			"max_dialog_rounds": map[string]interface{}{
		"type": "integer",
	},
			"provider": map[string]interface{}{
		"type": "string",
		"enum": []string{"openai", "grok", "anthropic"},
	},
			"output_description": map[string]interface{}{
		"type": "string",
	},
			"role": map[string]interface{}{
		"type": "string",
	},
			"model": map[string]interface{}{
		"type": "string",
	},
			"reasoning": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"name", "input_description", "needs_dialog", "max_dialog_rounds", "provider", "output_description", "role", "model", "reasoning"},
		"additionalProperties": false,
	},
	"GenerationInput": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"user_answers": map[string]interface{}{
		"type": "object",
		"additionalProperties": true,
	},
			"analysis": map[string]interface{}{
		"type": "string",
	},
			"refinement_instructions": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"user_answers", "analysis", "refinement_instructions"},
		"additionalProperties": false,
	},
	"TypeDefinition": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"description": map[string]interface{}{
		"type": "string",
	},
			"name": map[string]interface{}{
		"type": "string",
	},
			"fields": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"field_name": map[string]interface{}{
		"type": "string",
	},
			"field_type": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"field_name", "field_type"},
		"additionalProperties": false,
	},
	},
		},
		"required": []string{"description", "name", "fields"},
		"additionalProperties": false,
	},
	"GeneratedConfig": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"agent_count": map[string]interface{}{
		"type": "integer",
	},
			"validation_status": map[string]interface{}{
		"type": "string",
		"enum": []string{"valid", "invalid", "warning"},
	},
			"validation_notes": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"field": map[string]interface{}{
		"type": "string",
	},
			"severity": map[string]interface{}{
		"type": "string",
		"enum": []string{"error", "warning", "info"},
	},
			"message": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"field", "severity", "message"},
		"additionalProperties": false,
	},
	},
			"improvement_suggestions": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "string",
	},
	},
			"version": map[string]interface{}{
		"type": "string",
	},
			"assistants": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"name": map[string]interface{}{
		"type": "string",
	},
			"system_prompt": map[string]interface{}{
		"type": "string",
	},
			"needs_dialog": map[string]interface{}{
		"type": "boolean",
	},
			"dialog_max_rounds": map[string]interface{}{
		"type": "integer",
	},
			"input_type": map[string]interface{}{
		"type": "string",
	},
			"needs_thread": map[string]interface{}{
		"type": "boolean",
	},
			"use": map[string]interface{}{
		"type": "string",
		"enum": []string{"openai", "grok", "anthropic"},
	},
			"model": map[string]interface{}{
		"type": "string",
	},
			"output_type": map[string]interface{}{
		"type": "string",
	},
			"max_tokens": map[string]interface{}{
		"type": "integer",
	},
			"temperature": map[string]interface{}{
		"type": "number",
	},
		},
		"required": []string{"name", "system_prompt", "needs_dialog", "dialog_max_rounds", "input_type", "needs_thread", "use", "model", "output_type", "max_tokens", "temperature"},
		"additionalProperties": false,
	},
	},
			"yaml_content": map[string]interface{}{
		"type": "string",
	},
			"notes": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "string",
	},
	},
			"type_count": map[string]interface{}{
		"type": "integer",
	},
			"types": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"description": map[string]interface{}{
		"type": "string",
	},
			"name": map[string]interface{}{
		"type": "string",
	},
			"fields": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"field_name": map[string]interface{}{
		"type": "string",
	},
			"field_type": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"field_name", "field_type"},
		"additionalProperties": false,
	},
	},
		},
		"required": []string{"description", "name", "fields"},
		"additionalProperties": false,
	},
	},
			"generated_at": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"agent_count", "validation_status", "validation_notes", "improvement_suggestions", "version", "assistants", "yaml_content", "notes", "type_count", "types", "generated_at"},
		"additionalProperties": false,
	},
	"ClarificationQuestion": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"question": map[string]interface{}{
		"type": "string",
	},
			"reason": map[string]interface{}{
		"type": "string",
	},
			"suggestions": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "string",
	},
	},
		},
		"required": []string{"question", "reason", "suggestions"},
		"additionalProperties": false,
	},
	"TaskAnalysis": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"complexity_score": map[string]interface{}{
		"type": "number",
	},
			"agents": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"needs_dialog": map[string]interface{}{
		"type": "boolean",
	},
			"max_dialog_rounds": map[string]interface{}{
		"type": "integer",
	},
			"provider": map[string]interface{}{
		"type": "string",
		"enum": []string{"openai", "grok", "anthropic"},
	},
			"output_description": map[string]interface{}{
		"type": "string",
	},
			"role": map[string]interface{}{
		"type": "string",
	},
			"model": map[string]interface{}{
		"type": "string",
	},
			"reasoning": map[string]interface{}{
		"type": "string",
	},
			"name": map[string]interface{}{
		"type": "string",
	},
			"input_description": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"needs_dialog", "max_dialog_rounds", "provider", "output_description", "role", "model", "reasoning", "name", "input_description"},
		"additionalProperties": false,
	},
	},
			"questions": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"question": map[string]interface{}{
		"type": "string",
	},
			"reason": map[string]interface{}{
		"type": "string",
	},
			"suggestions": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "string",
	},
	},
		},
		"required": []string{"question", "reason", "suggestions"},
		"additionalProperties": false,
	},
	},
			"requires_thread": map[string]interface{}{
		"type": "boolean",
	},
			"requires_dialog": map[string]interface{}{
		"type": "boolean",
	},
			"summary": map[string]interface{}{
		"type": "string",
	},
			"needs_clarification": map[string]interface{}{
		"type": "boolean",
	},
			"architecture_notes": map[string]interface{}{
		"type": "string",
	},
			"agent_count": map[string]interface{}{
		"type": "integer",
	},
			"data_types_needed": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "string",
	},
	},
			"implementation_hints": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "string",
	},
	},
			"complexity": map[string]interface{}{
		"type": "string",
		"enum": []string{"simple", "medium", "complex", "very_complex"},
	},
		},
		"required": []string{"complexity_score", "agents", "questions", "requires_thread", "requires_dialog", "summary", "needs_clarification", "architecture_notes", "agent_count", "data_types_needed", "implementation_hints", "complexity"},
		"additionalProperties": false,
	},
	"AssistantConfig": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"dialog_max_rounds": map[string]interface{}{
		"type": "integer",
	},
			"input_type": map[string]interface{}{
		"type": "string",
	},
			"needs_thread": map[string]interface{}{
		"type": "boolean",
	},
			"use": map[string]interface{}{
		"type": "string",
		"enum": []string{"openai", "grok", "anthropic"},
	},
			"model": map[string]interface{}{
		"type": "string",
	},
			"output_type": map[string]interface{}{
		"type": "string",
	},
			"max_tokens": map[string]interface{}{
		"type": "integer",
	},
			"temperature": map[string]interface{}{
		"type": "number",
	},
			"name": map[string]interface{}{
		"type": "string",
	},
			"system_prompt": map[string]interface{}{
		"type": "string",
	},
			"needs_dialog": map[string]interface{}{
		"type": "boolean",
	},
		},
		"required": []string{"dialog_max_rounds", "input_type", "needs_thread", "use", "model", "output_type", "max_tokens", "temperature", "name", "system_prompt", "needs_dialog"},
		"additionalProperties": false,
	},
	"FieldDefinition": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"field_type": map[string]interface{}{
		"type": "string",
	},
			"field_name": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"field_type", "field_name"},
		"additionalProperties": false,
	},
	"ValidationNote": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"severity": map[string]interface{}{
		"type": "string",
		"enum": []string{"error", "warning", "info"},
	},
			"message": map[string]interface{}{
		"type": "string",
	},
			"field": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"severity", "message", "field"},
		"additionalProperties": false,
	},
}
// ============ HELPERS ============

