// Code generated by aiwf. DO NOT EDIT.

package metasdk

// FieldDefinition represents FieldDefinition
type FieldDefinition struct {
	FieldType string `json:"field_type"`
	FieldName string `json:"field_name"`
}

// TypeDefinition represents TypeDefinition
type TypeDefinition struct {
	Fields []*FieldDefinition `json:"fields"`
	Description string `json:"description"`
	Name string `json:"name"`
}

// ValidationNote represents ValidationNote
type ValidationNote struct {
	Field string `json:"field"`
	Severity string `json:"severity"`
	Message string `json:"message"`
}

// AssistantConfig represents AssistantConfig
type AssistantConfig struct {
	Temperature float64 `json:"temperature"`
	Use string `json:"use"`
	NeedsDialog bool `json:"needs_dialog"`
	Name string `json:"name"`
	InputTypeRef *TypeReference `json:"input_type_ref"`
	OutputTypeRef *TypeReference `json:"output_type_ref"`
	MaxTokens int `json:"max_tokens"`
	DialogMaxRounds int `json:"dialog_max_rounds"`
	Model string `json:"model"`
	SystemPrompt string `json:"system_prompt"`
	NeedsThread bool `json:"needs_thread"`
}

// GeneratedConfig represents GeneratedConfig
type GeneratedConfig struct {
	Types []*TypeDefinition `json:"types"`
	YamlContent string `json:"yaml_content"`
	AgentCount int `json:"agent_count"`
	Assistants []*AssistantConfig `json:"assistants"`
	ValidationStatus string `json:"validation_status"`
	ImprovementSuggestions []string `json:"improvement_suggestions"`
	TypeCount int `json:"type_count"`
	ValidationNotes []*ValidationNote `json:"validation_notes"`
	Notes []string `json:"notes"`
	Version string `json:"version"`
	GeneratedAt string `json:"generated_at"`
}

// AgentSpec represents AgentSpec
type AgentSpec struct {
	Role string `json:"role"`
	Provider string `json:"provider"`
	OutputDescription string `json:"output_description"`
	Reasoning string `json:"reasoning"`
	Name string `json:"name"`
	Model string `json:"model"`
	NeedsDialog bool `json:"needs_dialog"`
	MaxDialogRounds int `json:"max_dialog_rounds"`
	InputDescription string `json:"input_description"`
}

// ClarificationQuestion represents ClarificationQuestion
type ClarificationQuestion struct {
	Reason string `json:"reason"`
	Suggestions []string `json:"suggestions"`
	Question string `json:"question"`
}

// TaskAnalysis represents TaskAnalysis
type TaskAnalysis struct {
	Agents []*AgentSpec `json:"agents"`
	RequiresThread bool `json:"requires_thread"`
	DataTypesNeeded []string `json:"data_types_needed"`
	ImplementationHints []string `json:"implementation_hints"`
	AgentCount int `json:"agent_count"`
	NeedsClarification bool `json:"needs_clarification"`
	Summary string `json:"summary"`
	Complexity string `json:"complexity"`
	RequiresDialog bool `json:"requires_dialog"`
	Questions []*ClarificationQuestion `json:"questions"`
	ArchitectureNotes string `json:"architecture_notes"`
	ComplexityScore float64 `json:"complexity_score"`
}

// UserAnswer represents UserAnswer
type UserAnswer struct {
	Question string `json:"question"`
	Answer string `json:"answer"`
}

// TypeReference represents TypeReference
type TypeReference struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
}

// GenerationInput represents GenerationInput
type GenerationInput struct {
	RefinementInstructions string `json:"refinement_instructions"`
	UserAnswers []*UserAnswer `json:"user_answers"`
	Analysis string `json:"analysis"`
}

// ============ VALIDATORS ============

// ValidateAgentSpec validates AgentSpec
func ValidateAgentSpec(v *AgentSpec) error {
	// No validation rules
	return nil
}

// ValidateClarificationQuestion validates ClarificationQuestion
func ValidateClarificationQuestion(v *ClarificationQuestion) error {
	// No validation rules
	return nil
}

// ValidateTaskAnalysis validates TaskAnalysis
func ValidateTaskAnalysis(v *TaskAnalysis) error {
	// No validation rules
	return nil
}

// ValidateUserAnswer validates UserAnswer
func ValidateUserAnswer(v *UserAnswer) error {
	// No validation rules
	return nil
}

// ValidateTypeReference validates TypeReference
func ValidateTypeReference(v *TypeReference) error {
	// No validation rules
	return nil
}

// ValidateGenerationInput validates GenerationInput
func ValidateGenerationInput(v *GenerationInput) error {
	// No validation rules
	return nil
}

// ValidateFieldDefinition validates FieldDefinition
func ValidateFieldDefinition(v *FieldDefinition) error {
	// No validation rules
	return nil
}

// ValidateTypeDefinition validates TypeDefinition
func ValidateTypeDefinition(v *TypeDefinition) error {
	// No validation rules
	return nil
}

// ValidateValidationNote validates ValidationNote
func ValidateValidationNote(v *ValidationNote) error {
	// No validation rules
	return nil
}

// ValidateAssistantConfig validates AssistantConfig
func ValidateAssistantConfig(v *AssistantConfig) error {
	// No validation rules
	return nil
}

// ValidateGeneratedConfig validates GeneratedConfig
func ValidateGeneratedConfig(v *GeneratedConfig) error {
	// No validation rules
	return nil
}

// ============ TYPE METADATA ============

// TypeMetadata exports type definitions for providers
var TypeMetadata = map[string]interface{}{
	"ValidationNote": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"message": map[string]interface{}{
		"type": "string",
	},
			"field": map[string]interface{}{
		"type": "string",
	},
			"severity": map[string]interface{}{
		"type": "string",
		"enum": []string{"error", "warning", "info"},
	},
		},
		"required": []string{"message", "field", "severity"},
		"additionalProperties": false,
	},
	"AssistantConfig": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"input_type_ref": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"name": map[string]interface{}{
		"type": "string",
	},
			"kind": map[string]interface{}{
		"type": "string",
		"enum": []string{"primitive", "custom"},
	},
		},
		"required": []string{"name", "kind"},
		"additionalProperties": false,
	},
			"output_type_ref": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"name": map[string]interface{}{
		"type": "string",
	},
			"kind": map[string]interface{}{
		"type": "string",
		"enum": []string{"primitive", "custom"},
	},
		},
		"required": []string{"name", "kind"},
		"additionalProperties": false,
	},
			"max_tokens": map[string]interface{}{
		"type": "integer",
	},
			"dialog_max_rounds": map[string]interface{}{
		"type": "integer",
	},
			"model": map[string]interface{}{
		"type": "string",
	},
			"system_prompt": map[string]interface{}{
		"type": "string",
	},
			"needs_thread": map[string]interface{}{
		"type": "boolean",
	},
			"temperature": map[string]interface{}{
		"type": "number",
	},
			"use": map[string]interface{}{
		"type": "string",
		"enum": []string{"openai", "grok", "anthropic"},
	},
			"needs_dialog": map[string]interface{}{
		"type": "boolean",
	},
			"name": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"input_type_ref", "output_type_ref", "max_tokens", "dialog_max_rounds", "model", "system_prompt", "needs_thread", "temperature", "use", "needs_dialog", "name"},
		"additionalProperties": false,
	},
	"GeneratedConfig": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"types": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"fields": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"field_name": map[string]interface{}{
		"type": "string",
	},
			"field_type": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"field_name", "field_type"},
		"additionalProperties": false,
	},
	},
			"description": map[string]interface{}{
		"type": "string",
	},
			"name": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"fields", "description", "name"},
		"additionalProperties": false,
	},
	},
			"yaml_content": map[string]interface{}{
		"type": "string",
	},
			"agent_count": map[string]interface{}{
		"type": "integer",
	},
			"assistants": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"input_type_ref": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"name": map[string]interface{}{
		"type": "string",
	},
			"kind": map[string]interface{}{
		"type": "string",
		"enum": []string{"primitive", "custom"},
	},
		},
		"required": []string{"name", "kind"},
		"additionalProperties": false,
	},
			"output_type_ref": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"name": map[string]interface{}{
		"type": "string",
	},
			"kind": map[string]interface{}{
		"type": "string",
		"enum": []string{"primitive", "custom"},
	},
		},
		"required": []string{"name", "kind"},
		"additionalProperties": false,
	},
			"max_tokens": map[string]interface{}{
		"type": "integer",
	},
			"dialog_max_rounds": map[string]interface{}{
		"type": "integer",
	},
			"model": map[string]interface{}{
		"type": "string",
	},
			"system_prompt": map[string]interface{}{
		"type": "string",
	},
			"needs_thread": map[string]interface{}{
		"type": "boolean",
	},
			"temperature": map[string]interface{}{
		"type": "number",
	},
			"use": map[string]interface{}{
		"type": "string",
		"enum": []string{"openai", "grok", "anthropic"},
	},
			"needs_dialog": map[string]interface{}{
		"type": "boolean",
	},
			"name": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"input_type_ref", "output_type_ref", "max_tokens", "dialog_max_rounds", "model", "system_prompt", "needs_thread", "temperature", "use", "needs_dialog", "name"},
		"additionalProperties": false,
	},
	},
			"validation_status": map[string]interface{}{
		"type": "string",
		"enum": []string{"valid", "invalid", "warning"},
	},
			"improvement_suggestions": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "string",
	},
	},
			"type_count": map[string]interface{}{
		"type": "integer",
	},
			"validation_notes": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"severity": map[string]interface{}{
		"type": "string",
		"enum": []string{"error", "warning", "info"},
	},
			"message": map[string]interface{}{
		"type": "string",
	},
			"field": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"severity", "message", "field"},
		"additionalProperties": false,
	},
	},
			"notes": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "string",
	},
	},
			"version": map[string]interface{}{
		"type": "string",
	},
			"generated_at": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"types", "yaml_content", "agent_count", "assistants", "validation_status", "improvement_suggestions", "type_count", "validation_notes", "notes", "version", "generated_at"},
		"additionalProperties": false,
	},
	"AgentSpec": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"name": map[string]interface{}{
		"type": "string",
	},
			"model": map[string]interface{}{
		"type": "string",
	},
			"needs_dialog": map[string]interface{}{
		"type": "boolean",
	},
			"max_dialog_rounds": map[string]interface{}{
		"type": "integer",
	},
			"input_description": map[string]interface{}{
		"type": "string",
	},
			"role": map[string]interface{}{
		"type": "string",
	},
			"provider": map[string]interface{}{
		"type": "string",
		"enum": []string{"openai", "grok", "anthropic"},
	},
			"output_description": map[string]interface{}{
		"type": "string",
	},
			"reasoning": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"name", "model", "needs_dialog", "max_dialog_rounds", "input_description", "role", "provider", "output_description", "reasoning"},
		"additionalProperties": false,
	},
	"ClarificationQuestion": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"reason": map[string]interface{}{
		"type": "string",
	},
			"suggestions": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "string",
	},
	},
			"question": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"reason", "suggestions", "question"},
		"additionalProperties": false,
	},
	"TaskAnalysis": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"needs_clarification": map[string]interface{}{
		"type": "boolean",
	},
			"summary": map[string]interface{}{
		"type": "string",
	},
			"complexity": map[string]interface{}{
		"type": "string",
		"enum": []string{"simple", "medium", "complex", "very_complex"},
	},
			"requires_dialog": map[string]interface{}{
		"type": "boolean",
	},
			"questions": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"question": map[string]interface{}{
		"type": "string",
	},
			"reason": map[string]interface{}{
		"type": "string",
	},
			"suggestions": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "string",
	},
	},
		},
		"required": []string{"question", "reason", "suggestions"},
		"additionalProperties": false,
	},
	},
			"architecture_notes": map[string]interface{}{
		"type": "string",
	},
			"complexity_score": map[string]interface{}{
		"type": "number",
	},
			"agents": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"role": map[string]interface{}{
		"type": "string",
	},
			"provider": map[string]interface{}{
		"type": "string",
		"enum": []string{"openai", "grok", "anthropic"},
	},
			"output_description": map[string]interface{}{
		"type": "string",
	},
			"reasoning": map[string]interface{}{
		"type": "string",
	},
			"name": map[string]interface{}{
		"type": "string",
	},
			"model": map[string]interface{}{
		"type": "string",
	},
			"needs_dialog": map[string]interface{}{
		"type": "boolean",
	},
			"max_dialog_rounds": map[string]interface{}{
		"type": "integer",
	},
			"input_description": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"role", "provider", "output_description", "reasoning", "name", "model", "needs_dialog", "max_dialog_rounds", "input_description"},
		"additionalProperties": false,
	},
	},
			"requires_thread": map[string]interface{}{
		"type": "boolean",
	},
			"data_types_needed": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "string",
	},
	},
			"implementation_hints": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "string",
	},
	},
			"agent_count": map[string]interface{}{
		"type": "integer",
	},
		},
		"required": []string{"needs_clarification", "summary", "complexity", "requires_dialog", "questions", "architecture_notes", "complexity_score", "agents", "requires_thread", "data_types_needed", "implementation_hints", "agent_count"},
		"additionalProperties": false,
	},
	"UserAnswer": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"question": map[string]interface{}{
		"type": "string",
	},
			"answer": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"question", "answer"},
		"additionalProperties": false,
	},
	"TypeReference": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"name": map[string]interface{}{
		"type": "string",
	},
			"kind": map[string]interface{}{
		"type": "string",
		"enum": []string{"primitive", "custom"},
	},
		},
		"required": []string{"name", "kind"},
		"additionalProperties": false,
	},
	"GenerationInput": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"refinement_instructions": map[string]interface{}{
		"type": "string",
	},
			"user_answers": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"question": map[string]interface{}{
		"type": "string",
	},
			"answer": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"question", "answer"},
		"additionalProperties": false,
	},
	},
			"analysis": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"refinement_instructions", "user_answers", "analysis"},
		"additionalProperties": false,
	},
	"FieldDefinition": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"field_name": map[string]interface{}{
		"type": "string",
	},
			"field_type": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"field_name", "field_type"},
		"additionalProperties": false,
	},
	"TypeDefinition": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"name": map[string]interface{}{
		"type": "string",
	},
			"fields": map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
		"type": "object",
		"properties": map[string]interface{}{
			"field_name": map[string]interface{}{
		"type": "string",
	},
			"field_type": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"field_name", "field_type"},
		"additionalProperties": false,
	},
	},
			"description": map[string]interface{}{
		"type": "string",
	},
		},
		"required": []string{"name", "fields", "description"},
		"additionalProperties": false,
	},
}
// ============ HELPERS ============

