version: 0.1
schema_registry:
  root: schemas

assistants:
  outline:
    model: gpt-4o-mini
    system_prompt: |
      You are an editorial planner. Produce a catchy title and a list of sections for a blog post.
    input_schema_ref: outline_input.json
    output_schema_ref: outline_output.json
  draft:
    model: gpt-4o
    system_prompt: |
      Write a concise blog post section by section.
    input_schema_ref: draft_input.json
    output_schema_ref: draft_output.json

workflows:
  blog_post:
    description: Generate a blog post outline and draft content.
    dag:
      - step: outline
        assistant: outline
      - step: draft
        assistant: draft
        needs: [outline]
